#! /usr/bin/env python
# encoding: utf-8


def options(opt): pass


def configure(conf): pass


def build(bld):
	bld.shlib(
		source = 'hdfs_httpfs.cpp gateway.cpp file.cpp dir.cpp httpfs_site.cpp',
		target = 'hdfs_httpfs',
		use = 'PFICOMMON')
